@echo off
set PATH=c:\j2sdk1.4.0\bin;%PATH%
set PACKAGE=com\mrjc\twiki\addons
set ECLIPSEPROJECTDIR=c:\eclipse\workspace\JavaPasteAddOn\%PACKAGE%
set SOURCEFILES=%ECLIPSEPROJECTDIR%\*.class
set JAVAPASTEDIR=c:\javapaste
set TEMPBASEDIR=%JAVAPASTEDIR%\Temp
set TEMPDIR=%TEMPBASEDIR%\%PACKAGE%
set UNSIGNEDJAR=%JAVAPASTEDIR%\TWikiPasteUnsigned.jar
set SIGNEDJAR=%JAVAPASTEDIR%\TWikiPasteSigned.jar
set LOCALUSERPROFILEDIR=c:\WINNT\Profiles\Cmacleod
set CERTIFICATEFILE=c:\javapaste\TWikiCertificate.cer
set KEYSTORE=ks0001
set KEYPASS=kp0001
set STOREPASS=usp0001
set KEYSTOREALIAS=TWikiStoreAlias