
sfdistro :
	tar cjf sfwiki.tar.bz2 README install_twiki.cgi pre-twiki.sh post-twiki.sh un-twiki.sh downloads cpan/MIRROR/TWIKI


#cpan :
#	cd cpan ; ./mirror-cpan.pl `./calc-twiki-deps.pl`

#downloads/releases/TWiki20040901.tar.gz :
#	wget -O downloads/releases/TWiki20040901.tar.gz http://twiki.org/releases/TWiki20040901.tar.gz
#	wget -O downloads/releases/TWiki20040901.tar.gz http://twikiplugins.sourceforge.net/releases/TWiki20040901.tar.gz

#downloads/plugins :
#	bin/download-twiki-plugins.pl 
#	bin/zip2tgz downloads/plugins

#downloads/contib :
#	bin/download-twiki-contribs.pl 
#	bin/zip2tgz downloads/contrib

#downloads/addons :
#	bin/download-twiki-addons.pl 
#	bin/zip2tgz downloads/addons

