PATENT_LINK_PLUGIN_ROOT=${HOME}/dv/twikiplugins/PatentLinkPlugin
TWIKIHOME=${HOME}/www/twiki

install:
	cp -vu ${PATENT_LINK_PLUGIN_ROOT}/lib/TWiki/Plugins/PatentLinkPlugin.pm ${TWIKIHOME}/lib/TWiki/Plugins/
	cp -vu ${PATENT_LINK_PLUGIN_ROOT}/data/TWiki/PatentLinkPlugin.txt ${TWIKIHOME}/data/TWiki/
