#!/usr/bin/perl -w
#
# TWiki Enterprise Collaboration Platform, http://TWiki.org/
#
# Copyright (C) 2006-2012 TWiki Contributors.
# All Rights Reserved. TWiki Contributors are listed in
# the AUTHORS file in the root of this distribution.
# NOTE: Please extend that file, not this notice.

use Net::LDAP;

# usage: ldaptet 'ldap-query'

## PLEASE MODIFIY #############################################

# server name or IP address
my $server = 'localhost';

# dn from where searches are performed recursively
my $baseDN = 'dc=nodomain';

# username and credentials used to connect to the LDAP server;
# if unset an anonymous connect will be used
# CAUTION: when typing in a password, this is plain text. 
# please make sure that this file is only readable for authorized personell
my $bindUser = ''; 
my $bindPassword = '';

# maximum number of records returned
my $sizeLimit = 10;

###############################################################

my $filter = $ARGV[0] || '(objectClass=*)';

my $ldap = Net::LDAP->new($server) || die "$@";

my $mesg;
if ($bindUser) {
  $mesg = $ldap->bind($bindUser, password=>$bindPassword);
} else {
  $mesg = $ldap->bind();
}
my $code = $mesg->code;
$code && die "Bind error, code $code, message: ".$mesg->error;
$mesg = $ldap->search(
  filter=>$filter,
  base=>$baseDN,
  sizelimit=>$sizeLimit,
);
$code = $mesg->code;
if ($code && $code != 4) {
  die "Search error, code: $code, message: ".$mesg->error;
}

my @entries = $mesg->entries;
foreach $entry (@entries) {
  $entry->dump;
}
