#!/usr/bin/perl -w
#
# Module for TWiki Enterprise Collaboration Platform, http://TWiki.org/
#
# Copyright (C) 2012 Peter Thoeny, peter[at]thoeny.org and
# TWiki Contributors.
# All Rights Reserved. TWiki Contributors are listed in
# the AUTHORS file in the root of this distribution.
# NOTE: Please extend that file, not this notice.
#
# usage:
#   # perl ldapdump ./cache.db > dump.txt

use DB_File;
use Data::Dumper;

my $cacheFile = $ARGV[0] || die "Please specify cache.db file";
my %data;
tie %data, 'DB_File', $cacheFile, O_RDONLY, 0664
or die "Cannot open file $cacheFile: $!";
print Dumper( \%data );

