#!/bin/bash
# to be run in crontab, at regular intervals (shorter than cleargracemin)
# e.g.:
# */3 * * * * test -x $dest/pccl && $dest/pccl

# options:
# -n    do nothing, just prints the status of changers

bin=XXXbinXXX
view=XXXviewXXX
data=XXXdataXXX
cache=XXXcacheXXX
cleargrace=XXXcleargraceXXX
cleargracemin=XXXcleargraceminXXX
binurl=XXXbinurlXXX

# Actually, we should not use these as we are not running under the web server
# UID, to avoid permissiond enied errors. Use at yur own risks
L () { date +"| %d %b %Y - %H:%M | guest | view | ${2#.} | $1 | $REMOTE_ADDR |" >>$logs/`date +'log%Y%m.txt'`; }
W () { echo `date '+%Y-%m-%d.%H:%M'` "$@" >>$logs/twpc-warnings.txt; }
D () { echo `date '+%Y-%m-%d.%H:%M'` "$@" >>$logs/twpc-debug.txt; }


shopt -s nullglob
if test "x$1" = x-n; then stats=true; else stats=false; fi

# times since last edit
max_d=0
let 'min_d=1<<31'
virgin=true

# clean pcbd tmp leftovers
test -d "${cache}_tmp" && \
    find "${cache}_tmp" -type f -mmin +60 -exec rm -f {} \;

for i in "$cache/_changers"/*; do
  # check that timeout is not over
  change=`date -r $i +'%s'`
  now=`date +'%s'`
  # D "${i##*/} change=$change now=$now diff=`let 'd=now-change';echo $d`"
  let 'd=now-change'
  if let 'd>max_d'; then max_d=$d
  elif let 'd<min_d'; then min_d=$d
  fi
  if $stats; then
    ip="${i##*/}"
    if host $ip >/dev/null 2>&1; then ipname="$ip (`host $ip|head -1 |sed -e 's/.* //'`)"
    else ipname="$ip"
    fi
    if $virgin; then 
      echo "Current changers (people having edited pages):"
      virgin=false
    fi
    echo "  $ipname last edit ${d} s ago"
  fi
done

if $stats; then # do nothing, print stats
  if $virgin; then
    echo "No edits in progress."
  else
    echo "Cache \"cleargrace\" settings: -t$cleargrace -T$cleargracemin (seconds)"
    echo -n "Time since last change: max = $max_d s"
    if let "$min_d != 1<<31"; then echo ", min = $min_d s"; else echo; fi
    if let 'max_d > cleargrace && min_d > cleargracemin' ; then
      echo "Cache will be cleared at next run of the pccl daemon"
    else
      let 'ct_max=cleargrace-max_d'
      let 'ct_min=cleargracemin-min_d'
      if let 'ct_min>ct_max'; then ct_max="$ct_min"; fi
      echo "Cache will be cleared at first run of the pccl daemon after ${ct_max} s from now"
    fi
  fi
else # do the real job
  # at least one changer had done nothing since cleargrace, and all the others
  # till cleargracemin (to avoid resetting cache during edits)
  if let 'max_d > cleargrace && min_d > cleargracemin' ; then
    wget -q -O /dev/null "$binurl/pcad?clear_changer"
    exit 0
  fi
  # expire timed caches by %PCACHEEXPTIME{...}% variable
  # performs the remove via pcad, buffers the requests for efficiency
  if cd "$cache/_expire" 2>/dev/null; then
    find . -type f -size 0 -mmin +0 | ( unset u;  while read i; do
      if test -z "$u"; then u="XXXbinurlXXX/pcad?action=topics&topicslist=";fi
      if let "(${#u}+${#i})>2000"; then 
	wget -q -O /dev/null "$u"
	u="XXXbinurlXXX/pcad?action=topics&topicslist="
      fi
      u="$u$i,"
      done
      if test -n "$u"; then wget -q -O /dev/null "$u"; fi
    )
  fi
fi

### EMACS MODES
### Local Variables: ***
### mode:ksh ***
### End: ***
