#!/bin/sh
# Copyright (C) 2006 Michael Daum <micha@nats.informatik.uni-hamburg.de>
#  
# This file is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version. 
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY, to the extent permitted by law; without even the
# implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# VERSION: v0.01
#
# Requirements: mod_rewrite, realpath, dirname, date, wget, sed, egrep
#
# Installation:
#   1. store this file into a sensible location, e.g.
#      /home/www-data/bin/getfeeds (<getfeeds-prg>)
#
#   2. make a copy of the provided example configuration script called
#      getfeeds.conf and store it next to the getfeeds script, e.g.
#      /home/www-data/bin/getfeeds.conf (<getfeeds-conf>)
#
#   3. create a directory feeds under apache's document root (<feeds-dir>)
#      This is not created automatically!
#
#   4. customize the getfeeds.conf file:
#
#      a) add FEEDS_DIR=<feeds-dir> to getfeeds.conf 
#         default: $HOME/public_html/feeds
#
#      b) add VIEW_URL=<url-to-bin-twiki-view>
#         default:  http://localhost/cgi-bin/twiki/view
#
#      c) add TWIKI_DIR=<path-to-twiki-installation>
#         default: $HOME/twiki
#
#      d) optionally add LOG_FILE=<path-to-getfeeds-dot-log-file>
#         default: $TWIKI_DIR/data/getfeeds.log
#
#      e) optionally add EXCLUDE_TOPICS_PATTERN=<regexp-pattern-of-feeds-not-to-be-cached>
#         default: Base.txt
#
#      f) optionally add EXCLUDE_WEBS_PATTERN=<regexp-pattern-of-webs-not-to-be-cached>
#         default: Trash|Attic|TestCases|mime.types|RegistrationApprovals
#
#      g) optionally add SLEEP=<grace-time-seconds>
#         default: 10
#
#      you may temporarily switch off generating feeds by adding ENABLED=false
#      to getfeeds.conf
#
#   5. TEST the script. Call it by hand and see if the feeds are generated
#      
#      ls -l <feeds-dir>/*xml
#
#      and check if they are there and non-empty. If not then have a look at
#      the <path-to-getfeeds-dot-log-file> for any error message.
#
#   6. add the following url rewrite rules to $TWIKI_DIR/bin/.htaccess
#
#      RewriteEngine On
#      
#      RewriteCond %{QUERY_STRING}  ^$
#      RewriteRule view/(.*)/(Web(Rss|Atom)(Combined|Comments|Teaser)?)$ /feeds/$1$2.xml [L,T=application/rss+xml]
#
# 
#      
#   7. add the following line to the crontab of the user under which the twiki cgi runs
#      (e.g. www-data) by typing crontab -e
# 
#      0 */2 * * *  cd <getfeeds-prg>
#
#      Remember to replace <getfeeds-prg> with the full path of the getfeeds script
#      The above rule will regenerate the feeds every 2 hours. If you'd like to generate
#      the scripts more or less frequently then please have a look at the crontab (5) man page
# 
#  

# debug
set -x

if test ! -f "$1"; then
   echo "ERROR: please specify the full path and filename of the config file"
   exit 1
fi

EGREP_PRG=`which egrep`
if test -z "$EGREP_PRG"; then
   echo "ERROR: egrep not found"
   exit 1
fi

DATE_PRG=`which date`
if test -z "$DATE_PRG"; then
   echo "ERROR: date not found"
   exit 1
fi

WGET_PRG=`which wget`
if test -z "$WGET_PRG"; then
   echo "ERROR: wget not found"
   exit 1
fi

SED_PRG=`which sed`
if test -z "$SED_PRG"; then
   echo "ERROR: sed not found"
   exit 1
fi

function writeInfo () {
  $DATE_PRG +"*** %Y-%m-%d %k:%M:%S - $*"
}

# read the config file
#GETFEEDS_PRG=`$REALPATH_PRG $0`
#GETFEEDS_DIR=`$DIRNAME_PRG $GETFEEDS_PRG`
CONFIG_FILE=$1
test -f $CONFIG_FILE && . $CONFIG_FILE

# default values
test -z "$ENABLED" && ENABLED=true
test -z "$VIEW_URL" && VIEW_URL="http://localhost/cgi-bin/twiki/view"
test -z "$FEEDS_DIR" && FEEDS_DIR="$HOME/public_html/feeds"
test -z "$TWIKI_DIR" && TWIKI_DIR="$HOME/twiki"
test -z "$LOG_FILE" && LOG_FILE="$TWIKI_DIR/data/getfeeds.log"
test -z "$EXCLUDE_WEBS_PATTERN" && EXCLUDE_WEBS_PATTERN='Trash|Attic|TestCases|mime.types|RegistrationApprovals'
test -z "$EXCLUDE_TOPICS_PATTERN" && EXCLUDE_TOPICS_PATTERN="Base.txt"
test -z "$WEBS" && WEBS="`ls $TWIKI_DIR/data | $EGREP_PRG -v $EXCLUDE_WEBS_PATTERN | $EGREP_PRG -v '\.txt|\.log|^_'`"
test -z "$SLEEP" && SLEEP=10

(
  if test "$ENABLED" == "false"; then
    writeInfo "disabled"
    exit 0 
  fi

  writeInfo "starting $GETFEEDS_PRG"
  for WEB in $WEBS; do
    FEEDS="`ls $TWIKI_DIR/data/$WEB/WebRss*txt $TWIKI_DIR/data/$WEB/WebAtom*txt|$EGREP_PRG -v $EXCLUDE_TOPICS_PATTERN|$SED_PRG 's/^.*\/\(.*\)\.txt$/\1/g'`"
    for TOPIC in $FEEDS; do
      OUT_FILE="$FEEDS_DIR/$WEB$TOPIC.xml"
      TMP_FILE="/tmp/$WEB$TOPIC.xml"
      echo "*** fetching $WEB.$TOPIC into $OUT_FILE"
      $WGET_PRG -q -O $TMP_FILE $VIEW_URL/$WEB/$TOPIC?t=`$DATE_PRG +"%s"` && mv $TMP_FILE $OUT_FILE && chmod go+r $OUT_FILE
      sleep $SLEEP
    done
  done
  writeInfo "done $GETFEEDS_PRG"
) #>> $LOG_FILE 2>&1
