#!/usr/bin/perl
#
# Script to extract strings from TWiki sources and templates

use strict;
use Locale::Maketext::Extract::Run 'xgettext';

# force the use from the root
-d 'bin' and -d "lib" and -d 'tools' and -d 'templates' or die("You may only run this utility from the root directory of TWiki sources!");

# config
my $localesDir = "locale";
my $potfile = "${localesDir}/TWiki.pot";
my $newpotfile = $potfile . '.new';

# extract strings from the source code and append to the new potfile

#####################################################################
# driven from MANIFEST (picks up only files that are included in the release)
my @templates;
my @sources;
open(R, "<tools/MANIFEST") || die "Could not open tools/MANIFEST: $!";
foreach my $source (<R>) {
    chomp($source);
    if( $source =~ /^bin\/[a-z]/ || $source =~ /^lib\/.*\.pm$/ ||
        $source =~ /^templates\/.*\.tmpl$/ ) {
        push(@sources, $source);
    }
}
close(R);

#################### OR ########################
# driven from 
#my $bin = "find bin/* -name '[a-z]*'";
#my $lib = "find lib -name '*.pm'";
#system("($bin && $lib) > $sources_listing");
#my @templates = `find templates/*`;
#####################################################################

print("I: scanning sources, it may take some time...\n");
xgettext("-o", $newpotfile, @sources);

if (! -e $newpotfile) {
  # no extracted strings
  system("echo | xgettext --force-po --language=Perl --output=$newpotfile -"); #empty potfile
  print("W: no strings extracted from source: $newpotfile was not created.\n");
  exit 1;
}

#unify duplicates:
system("cp $newpotfile $newpotfile.orig && ( cat $newpotfile.orig | sed -e 's/CHARSET/UTF-8/' | msguniq --force-po --output=$newpotfile - ) && rm -f $newpotfile.orig"); 
print("I: unified duplicated strings.\n");

# merge with $potfile if it already exists, copy to it otherwise
if (-e "$potfile") {
  print("W: merging generated potfile ($newpotfile) with existing one ($potfile)\n");
  system("msgmerge --update $potfile $newpotfile");
} else {
  system("cp $newpotfile $potfile");
}

# merge with existing translations:
my @translations = `find ${localesDir}/ -name '*.po'`;
foreach my $translation (@translations) {
  chomp($translation);
  print("I: Merging $potfile into $translation.\n");
  system("msgmerge --update $translation $potfile");
}

# cleanup after generating base POT
print("I: Removing intermediate files\n");
system("rm -f $newpotfile");
