#!/bin/perl
chmod(0755, "bin/publish");
my $cfgFile = "lib/TWiki/Contrib/PublishAddOn/PublishAddOn.cfg";
my $dir;
my $url;
if( -e $cfgFile) {
    use vars qw( $PUBLISH_DIR $PUBLISH_URL );
    do $cfgFile;
    $dir = $PUBLISH_DIR;
    $url = $PUBLISH_URL;
}

print <<THIS;
##########################################################
You will now be prompted for a couple of paths. These paths have
to be stored on the server, and not in TWiki settings, for
security reasons.
THIS

my $reply = '';
while( $reply !~ /^y(es)?\b/i ) {
    while( $reply !~ /^y(es)?\b/i ) {
        my $wdir = '';
        $wdir = " ($dir)" if $dir;
        print "\nPlease enter the full path name of the directory where\npublished zip files will be stored$wdir: ";
        my $ndir = <STDIN>;
        chomp($ndir);
        $dir = $ndir if $ndir;
        if( -d $dir ) {
            $reply = 'yes';
        } else {
            print "The directory $dir does not exist; is that ok? [yes/no] ";
            $reply = <STDIN>;
            chomp($dir);
        }
    }

    my $wurl = '';
    $wurl = " ($url)" if $url;
    print "Please enter the full URL path to that directory$wurl: ";
    my $nurl = <STDIN>;
    chomp($nurl);
    $url = $nurl if $nurl;

    print "You entered:\nPUBLISH_DIR: $dir\nPUBLISH_URL: $url\nIs that correct? [yes/no] ";
    $reply = <STDIN>;
    chomp($reply);
}

open CFG, ">$cfgFile";
print CFG <<THIS;
# This is the publish add-on configuration file, automatically
# written by the installer.
\$PUBLISH_DIR = '$dir';
\$PUBLISH_URL = '$url';
1;
THIS
close(CFG);
print <<THIS;
You can always re-run this installer at any point to change these paths.
THIS
